on:
  push: 
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing action'
        run: pwd

      - uses: actions/checkout@v3

      - name: 'login'
        run: docker login --username ${{secrets.DOCKERUSERNAME}} --password ${{secrets.DOKCERTOKEN}}

      - name: 'build image'
        run: docker buld -t ${{secrets.DOCKERUSERNAME}}/newimage .
        
      - name: 'push image'
        run: docker push ${{secrets.DOCKERUSERNAME}}/newimage

      
