on:
  push: 
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing action'
        run: pwd

      - uses: actions/checkout@v3

      - name: 'login'
        run: docker login --username ${{secrets.DOCKERUSERNAME}} --password ${{secrets.DOKCERTOKEN}}

      
