on:
  push: 
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing action'
        run: pwd

      - name: 'test printing'
        run: echo mario 

      - name: 'listing folders'
        run: ls
